version: '3.8'
services:
  backend:
    restart: unless-stopped
    build: ./backend
    ports:
      - 4000:4000
    volumes:
      - ./backend:/usr/src/app
    command: yarn start:watch
    tty: true
    stdin_open: true
  frontend:
    restart: unless-stopped
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    links:
      - backend
    command: yarn start
    tty: true
    stdin_open: true
  database:
    restart: unless-stopped
    build: ./mongodb
    ports:
      - 5000:5000
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./mongodb/database:/data/db