version: '3.8'
services:
  backend:
    restart: unless-stopped
    build: ./backend
    ports:
      - 4000:4000
    volumes:
      - ./backend:/usr/src/app
    command: yarn start:watch
    tty: true
    stdin_open: true
  frontend:
    restart: unless-stopped
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    links:
      - backend
    command: yarn start
    tty: true
    stdin_open: true
