version: '3.8'
services:
  database:
    restart: unless-stopped
    image: mongo
    ports: [ '27017:27017' ]
    environment:
      # TODO : Have credentials hidden in env vars
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./database/database:/data/db
  backend:
    restart: unless-stopped
    build: ./backend
    ports:
      - 4000:4000
    volumes:
      - ./backend:/usr/src/app
    links:
      - database
    command: yarn start
    tty: true
    stdin_open: true
  frontend:
    restart: unless-stopped
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    links:
      - backend
    command: yarn start
    tty: true
    stdin_open: true
