name: Backend CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - develop
    # TODO : Add this back
    # paths:
    #   - 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-dependencies-
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Lint app
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build:all
