name: Frontend CI

on:
  push:
    branches:
      - feature/ci # TODO #36 : Change branch for develop
  pull_request:
    branches:
      - feature/ci # TODO #36 : Change branch for develop

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      # TODO #36 : Add step for yarn lint
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build
